const Articulos = [
  {
    id: 1,
    nombre: "Guitarra",
    precio: 130,
    categoria: "cuerda",
    descripcion: "",
    imagen: require("./assets/guitarra.jpg"),
  },
  {
    id: 2,
    nombre: "Flauta",
    precio: 250,
    categoria: "viento",
    descripcion: "",
    imagen: require("./"),
  },
  {
    id: 3,
    nombre: "Violín",
    precio: 400,
    categoria: "cuerda",
    descripcion: "",
    imagen: require("./"),
  },
  {
    id: 4,
    nombre: "Trompeta",
    precio: 300,
    categoria: "viento",
    descripcion: "",
    imagen: require("./"),
  },
  {
    id: 5,
    nombre: "Trombón",
    precio: 350,
    categoria: "viento",
    descripcion: "",
    imagen: require("./"),
  },
  {
    id: 6,
    nombre: "Tuba",
    precio: 230,
    categoria: "viento",
    descripcion: "",
    imagen: require("./"),
  },
  {
    id: 7,
    nombre: "Platos",
    precio: 100,
    categoria: "percusion",
    descripcion: "",
    imagen: require("./"),
  },
  {
    id: 8,
    nombre: "Tambor",
    precio: 94,
    categoria: "percusion",
    descripcion: "",
    imagen: require("./"),
  },
  {
    id: 9,
    nombre: "Carrillón de láminas",
    precio: 550,
    categoria: "percusion",
    descripcion: "",
    imagen: require("./"),
  },
  {
    id: 10,
    nombre: "Piano",
    precio: 1250,
    categoria: "cuerda",
    descripcion: "",
    imagen: require("./assets/piano.jpg"),
  },
];
export default Articulos;
